package com.sczy.common.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sczy.common.domain.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Emptcode = new Property(1, String.class, "emptcode", false, "EMPTCODE");
        public final static Property Emptname = new Property(2, String.class, "emptname", false, "EMPTNAME");
        public final static Property Remarks = new Property(3, String.class, "remarks", false, "REMARKS");
        public final static Property Rolecity = new Property(4, String.class, "rolecity", false, "ROLECITY");
        public final static Property Emptcity = new Property(5, String.class, "emptcity", false, "EMPTCITY");
        public final static Property Sessionid = new Property(6, String.class, "sessionid", false, "SESSIONID");
    }

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EMPTCODE\" TEXT," + // 1: emptcode
                "\"EMPTNAME\" TEXT," + // 2: emptname
                "\"REMARKS\" TEXT," + // 3: remarks
                "\"ROLECITY\" TEXT," + // 4: rolecity
                "\"EMPTCITY\" TEXT," + // 5: emptcity
                "\"SESSIONID\" TEXT);"); // 6: sessionid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String emptcode = entity.getEmptcode();
        if (emptcode != null) {
            stmt.bindString(2, emptcode);
        }
 
        String emptname = entity.getEmptname();
        if (emptname != null) {
            stmt.bindString(3, emptname);
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(4, remarks);
        }
 
        String rolecity = entity.getRolecity();
        if (rolecity != null) {
            stmt.bindString(5, rolecity);
        }
 
        String emptcity = entity.getEmptcity();
        if (emptcity != null) {
            stmt.bindString(6, emptcity);
        }
 
        String sessionid = entity.getSessionid();
        if (sessionid != null) {
            stmt.bindString(7, sessionid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String emptcode = entity.getEmptcode();
        if (emptcode != null) {
            stmt.bindString(2, emptcode);
        }
 
        String emptname = entity.getEmptname();
        if (emptname != null) {
            stmt.bindString(3, emptname);
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(4, remarks);
        }
 
        String rolecity = entity.getRolecity();
        if (rolecity != null) {
            stmt.bindString(5, rolecity);
        }
 
        String emptcity = entity.getEmptcity();
        if (emptcity != null) {
            stmt.bindString(6, emptcity);
        }
 
        String sessionid = entity.getSessionid();
        if (sessionid != null) {
            stmt.bindString(7, sessionid);
        }
    }

    @Override
    protected final void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // emptcode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // emptname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // remarks
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // rolecity
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // emptcity
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // sessionid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEmptcode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmptname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRemarks(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRolecity(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEmptcity(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSessionid(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
